### PR TITLE
add initial state of codereview pages

### PR DESCRIPTION
**Pull request by aelliott1485**
Adding pages for Code Review SE, starting with 2 pages

### CODE REVIEW

**Comment by WillSullivan** [comment]
That second page could use a little more detail, but nice!

**Comment by aelliott1485** [comment]
Okay thanks! Do I need to create an issue before the changes will be visible on the site?

**Comment by aelliott1485** [comment]
Hey I still don't see the Code Review items listed... would you have any time soon to look at it? It would be nice to use this site for more than just SO...

**Comment by WillSullivan** [comment]
Okay, so I figured out what the problem is... nothing got pulled into the repo because

> WillSullivan merged commit 7b29360 into WillSullivan:idownloadedbecouse 27 days ago

### idownloadedbecouse

I have no idea what's going on here. I don't have a repo called idownloadedbecouse. I got this repo, tho. If you want to submit a pull request to this repo we could get this done. But as it stands now, 

dafuq.

**Comment by WillSullivan** [comment]
Ah, I've figured it out. Okay, so you forked off some branch that I have no idea what's going on. I've nuked that branch. If you could fork from my master and then pick over your changes and submit another pull request? I've got no idea how all this got so screwed up :/

**Comment by aelliott1485** [comment]
Ah yes - I merged my changes from that branch into master and submitted a new pull request #107

**Pull request merged**
